### PR TITLE
Add category index.

### PR DESCRIPTION
**Pull request by tech4him1**
This creates an index for the `category` folder so that you can import all the packages at once if you want to. It is generated along with the categories by the `generate` script.

This should be completely backwards-compatible, because if someone tried to require `unicode/category` before, it would have thrown an error.

### CODE REVIEW

**Comment by tech4him1** [comment]
This works with the `slug` package for me.

**Review by tdanecker — APPROVED** [review]

**Comment by tech4him1** [comment]
@tdanecker Are there any other specific things that you would like to see improved on the generator?

**Comment by tech4him1** [comment]
@tdanecker Thank you! Are there any other specific things that you would like to see improved on the generator?

**Comment by tech4him1** [comment]
@tdanecker Would you mind making a patch release so that I can use this PR in my Lite version, or are you planning on waiting for the next Unicode release?

**Comment by amaramth** [comment]
Can you publish a new release (10.1.0?) ? I want to use this

**Pull request merged**
